name: Counting Pages of Wiener Diariums

on:
  workflow_dispatch:

jobs:
  download:
    name: ounting Pages of Wiener Diariums
    runs-on: ubuntu-latest
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v3
      - name: Install Python Packages
        run: pip install -r requirements.txt
      - name: upload data
        run: python count_pages.yml
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Added page count in data.csv